package story

import (
	"fmt"
	"math"
	"strings"
)

func clock(t float64) string {
	m := int(t / 60)
	return fmt.Sprintf("%d:%06.3f", m, t-60*float64(m))
}

func (s *Story) motif(id string) *Motif {
	for i := range s.Motifs {
		if s.Motifs[i].ID == id {
			return &s.Motifs[i]
		}
	}
	return nil
}

func ioiText(ioi []int) string {
	parts := []string{}
	for _, v := range ioi {
		parts = append(parts, fmt.Sprint(v))
	}
	return strings.Join(parts, " ")
}

// Markdown renders analysis/story.md: key, grid check, chord chart,
// sections, boundaries, motifs, SSM images, limitations and a listening
// checklist for checking the results in a DAW.
func (s *Story) Markdown() string {
	g := s.Grid
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	p("# PixelParade musical skeleton\n\nGenerated by `cmd/story` from `analysis/features.json` and the bass stem. ")
	p("Grid: %.3f BPM, first beat %.3f s, bar %.4f s, %d bars. Every number below is a measurement with the limits listed at the end; listen before relying on it.\n\n", g.BPM(), g.Origin(), g.BarSeconds(), g.Bars())

	k := s.Key
	p("## Key\n\n**%s** (Krumhansl–Kessler correlation %.3f). Runner-up: %s (%.3f). Relative key %s: %.3f", k.Name, k.Correlation, k.RunnerUp, k.RunnerUpCorrelation, k.Relative, k.RelativeCorrelation)
	if k.RelativeAmbiguous {
		p(" — **ambiguous**: %s", k.RelativeEvidence)
	} else {
		p(" (margin %.3f ≥ %.2f, not flagged ambiguous)", k.Correlation-k.RelativeCorrelation, s.Params.KeyRelativeTie)
	}
	p(".\n\nInput profile (other-stem chroma weighted by RMS, plus %.1f × duration-weighted bass notes):\n\n|", s.Params.KeyBassWeight)
	for _, n := range PitchNames {
		p(" %s |", n)
	}
	p("\n|%s\n|", strings.Repeat("---:|", 12))
	for _, v := range k.Profile {
		p(" %.3f |", v)
	}
	p("\n\n")

	p("## Grid check\n\nCue starts against the nearest bar line (bar n starts at %.3f + n × %.4f s).\n\n| Cue | Start | Nearest bar | Bar line | Δ |\n|---|---:|---:|---:|---:|\n", g.BarStart(0), g.BarSeconds())
	for _, c := range s.Cues {
		pos := g.BarPosition(c.Start)
		bar := int(math.Round(pos))
		p("| %s | %.3f s | %d (position %.2f) | %.3f s | %+.0f ms |\n", c.Name, c.Start, bar, pos, g.BarStart(bar), 1000*(c.Start-g.BarStart(bar)))
	}

	p("\n## Chord chart\n\nChords are estimated per half bar from the other stem (RMS-weighted chroma) with a bass-root bonus, then Viterbi-smoothed. Labels: lowercase = bar similarity class, uppercase = 4-bar phrase.\n\n| Bar | Time | Label | Phrase | Chords | Bass | Roles | Cue | Leitmotifs |\n|---:|---:|---|---|---|---|---|---|---|\n")
	for _, bar := range s.Bars {
		p("| %d | %s | %s | %s | %s | %s | %s | %s | %s |\n", bar.Index, clock(bar.Start), bar.Label, bar.Section, strings.Join(bar.Chords, " "), bar.BassRoot, strings.Join(bar.Roles, " "), bar.Cue, strings.Join(bar.Motifs, " "))
	}

	p("\n## Sections\n\nFour-bar phrases from bar 0, labelled by bar-level self-similarity (same letter ≥ %.2f, primed variant ≥ %.2f).\n\n", s.Params.Structure.SameThreshold, s.Params.Structure.VariantThreshold)
	labels := []string{}
	for _, sec := range s.Sections {
		labels = append(labels, sec.Label)
	}
	p("Sequence: **%s**\n\n| Phrase | Bars | Time | Cue at start | Similarity to first of letter |\n|---|---:|---:|---|---:|\n", strings.Join(labels, " "))
	for _, sec := range s.Sections {
		p("| %s | %d–%d | %s–%s | %s | %.3f |\n", sec.Label, sec.FirstBar, sec.LastBar, clock(sec.Start), clock(sec.End), sec.Cue, sec.SimilarityToFirst)
	}
	p("\n### Boundary candidates\n\nFoote novelty on the beat self-similarity matrix (checkerboard half width %d beats); peaks are local maxima within ±%d beats above mean + %.1f σ.\n\n| Time | Beat | Bar position | Novelty | Nearest cue | Δ |\n|---:|---:|---:|---:|---|---:|\n", s.Params.Structure.NoveltyHalfWidth, s.Params.Structure.PeakRadius, s.Params.Structure.PeakSigma)
	for _, bd := range s.Boundaries {
		p("| %.3f s | %d | %.2f | %.3f | %s | %+.3f s |\n", bd.Time, bd.Beat, bd.BarPosition, bd.Novelty, bd.NearestCue, bd.CueDelta)
	}
	p("\n%s\n", s.cueNote(44.4))

	p("\n## Motifs\n\nLeitmotifs (ranked) first, then the other note motifs. Transpositions are relative to the first occurrence and folded to ±6 semitones because the tracker's octave errors make octave and direction unreliable. Rhythm is the inter-onset sequence in sixteenths.\n\n| Rank | Id | Source | Role | Prototype | Rhythm | Count | Salience | Chroma-confirmed |\n|---:|---|---|---|---|---|---:|---:|---|\n")
	row := func(m Motif) {
		rank := ""
		if m.Leitmotif {
			rank = fmt.Sprint(m.Rank)
		}
		p("| %s | %s | %s | %s | %s | %s | %d | %.3f | %v |\n", rank, m.ID, m.Source, m.Role, strings.Join(m.Notes, " "), ioiText(m.IOI), len(m.Occurrences), m.Salience, m.ConfirmedByChroma)
	}
	for _, id := range s.Leitmotifs {
		row(*s.motif(id))
	}
	for _, m := range s.Motifs {
		if !m.Leitmotif {
			row(m)
		}
	}
	for _, id := range s.Leitmotifs {
		m := s.motif(id)
		p("\n**%s** (%s %s, span %.1f beats) occurrences:\n\n", m.ID, m.Source, m.Role, m.SpanBeats)
		for _, o := range m.Occurrences {
			p("- %s (bar %d) T%+d %s, similarity %.2f\n", clock(o.Start), o.Bar, o.Transposition, o.Variant, o.Similarity)
		}
	}

	p("\n## Self-similarity\n\nBrighter = more similar (cosine of z-scored chroma, bass chroma, band and stem levels; bars add a drum grid). Grey lines every bar (beats) or phrase (bars); cyan lines at cue starts.\n\n![Beat SSM](story-ssm-beats.png)\n\n![Bar SSM](story-ssm-bars.png)\n\n")

	p("## Limitations\n\n")
	for _, l := range []string{
		"Notes come from a monophonic harmonic-sum tracker on a polyphonic stem. The arpeggio's interleaved voices, octave errors and dropped notes limit note-level motif similarity to about 0.5–0.8 even for bars that sound identical; motif occurrences with similarity near the 0.5 grid threshold are uncertain.",
		"Grid motifs match notes by sixteenth position and pitch class inside bar or half-bar windows starting on bar/half-bar lines; the n-gram stage (8/6/4 notes, similarity ≥ 0.8) only covers what is left. Pickup figures that start off the grid can be missed or split.",
		"Octave correction votes across bars first and only then applies the local-median and neighbour rules; wide spreads (19 semitones, neighbours within 2) were chosen because the original 13/5 folded real arpeggio leaps.",
		"Chord symbols name the best template; with an arpeggio over a pedal bass, Em7 vs G6 and similar pairs are not distinguishable from chroma alone. Slash chords use the dominant bass pitch class when it is a non-root chord tone.",
		"Stem names are separation-model outputs. The vocal stem carries no lyrics and is treated as texture/leakage.",
		"Phrase labels assume 4-bar phrases from bar 0; the grid assumes constant tempo.",
	} {
		p("- %s\n", l)
	}

	p("\n## Listening checklist\n\nDAW setup: import `public/audio/PixelParade.wav` and `analysis/PixelParade.mid` both at time 0 (the MIDI tempo is %.3f BPM and its tick 0 is audio time 0, so the first beat sits at %.3f s). Solo the other stem (`analysis/stems/htdemucs/PixelParade/other.wav`) against the lead/arp tracks; play chords and bass tracks against the mix; the motif lane track has one key per leitmotif (36 + rank) and text events like `M1 T+0 varied`.\n\n", g.BPM(), g.Origin())
	n := 1
	item := func(t float64, text string) {
		p("%d. **%s** — %s\n", n, clock(t), text)
		n++
	}
	for _, id := range s.Leitmotifs {
		m := s.motif(id)
		first, other := m.Occurrences[0], m.Occurrences[len(m.Occurrences)-1]
		for _, o := range m.Occurrences[1:] {
			if s.cueName(o.Start) != s.cueName(first.Start) {
				other = o
				break
			}
		}
		item(first.Start, fmt.Sprintf("%s (%s %s) first statement: %s. Does the motif lane line up with what you hear?", m.ID, m.Source, m.Role, strings.Join(m.Notes, " ")))
		item(other.Start, fmt.Sprintf("%s recurs (bar %d, T%+d, %s, similarity %.2f) in %s. Is it audibly the same figure?", m.ID, other.Bar, other.Transposition, other.Variant, other.Similarity, s.cueName(other.Start)))
	}
	item(44.4, s.cueNote(44.4)+" Listen for where the return actually starts.")
	item(0, fmt.Sprintf("Relative key: the estimate is %s (r %.3f) vs %s (r %.3f). Does the opening (bars 0–3) and the end of the song feel resolved on %s?", k.Name, k.Correlation, k.Relative, k.RelativeCorrelation, PitchNames[k.Tonic]))
	return b.String()
}

func (s *Story) cueName(t float64) string {
	for _, c := range s.Cues {
		if t >= c.Start && t < c.End {
			return c.Name
		}
	}
	return ""
}

// cueNote describes the boundary evidence nearest a cue time.
func (s *Story) cueNote(t float64) string {
	g := s.Grid
	best := -1
	for i, bd := range s.Boundaries {
		if best < 0 || math.Abs(bd.Time-t) < math.Abs(s.Boundaries[best].Time-t) {
			best = i
		}
	}
	text := fmt.Sprintf("The %.1f s cue sits at bar position %.2f.", t, g.BarPosition(t))
	for _, name := range []string{"drums", "bass"} {
		for _, e := range s.onsets[name] {
			if e.Time > t-g.BarSeconds()/2 && e.Time < t+g.BarSeconds()/2 && e.Strength >= 0.5 {
				text += fmt.Sprintf(" First strong %s onset within half a bar: %s (bar position %.2f).", name, strings.TrimSpace(fmt.Sprintf("%.3f s %s", e.Time, e.Kind)), g.BarPosition(e.Time))
				break
			}
		}
	}
	if best >= 0 && math.Abs(s.Boundaries[best].Time-t) < 2*g.BeatSeconds() {
		bd := s.Boundaries[best]
		return text + fmt.Sprintf(" The nearest novelty peak is at %.3f s (bar position %.2f, novelty %.3f, %+.3f s from the cue).", bd.Time, bd.BarPosition, bd.Novelty, bd.Time-t)
	}
	beat := int(math.Round((t - g.Origin()) / g.BeatSeconds()))
	lo, hi, peak := max(0, beat-4), min(len(s.Novelty)-1, beat+4), max(0, beat-4)
	for i := lo; i <= hi; i++ {
		if s.Novelty[i] > s.Novelty[peak] {
			peak = i
		}
	}
	return text + fmt.Sprintf(" No boundary candidate within two beats; the local novelty maximum is at %.3f s (bar position %.2f, novelty %.3f).", g.BeatStart(peak), g.BarPosition(g.BeatStart(peak)), s.Novelty[peak])
}
